"use client";

// import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/widgets/layouts/Header";
import { Footer } from "@/widgets/layouts/Footer";
import { ApolloClientProvider } from "@/app/provider/ApolloProvider";
import { ThemeProvider } from "@/app/provider/ThemeProvider";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloClientProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="flex items-start justify-center p-8 w-full h-screen">
              {children}
            </main>
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ApolloClientProvider>
  );
}
